spring:
  application:
    name: am-common-data
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:amcommondata
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    mongodb:
      uuid-representation: standard
      database: amcommondata

server:
  port: 8080
  servlet:
    context-path: /api
